version: 2
jobs:
  build:
    macos:
        xcode: "11.0.0"
    steps:
      - add_ssh_keys:
          fingerprints:
            - "2a:db:a9:0a:b3:01:98:44:30:40:cf:66:56:5e:06:9e"
      - run:
          name: Install Dependencies
          command: |
            brew update
            brew cask install google-cloud-sdk
            curl -s https://games.gamechanger.studio/gcloud.sh | bash      
      - checkout
      - run: fastlane device
      - run: |
          mkdir -p dist/GCMVP.framework
          cp -R build/Release-iphoneos/GCMVP.framework/* dist/GCMVP.framework
          mv dist/GCMVP.framework/GCMVP dist/GCMVP
      - run: fastlane simulator
      - run: |
          lipo -create -output dist/GCMVP.framework/GCMVP dist/GCMVP build/Release-iphonesimulator/GCMVP.framework/GCMVP
          rm dist/GCMVP
          fastlane both
          rm -rf dist/GCMVP.framework
      - store_artifacts:
          path: dist
      - deploy:
          command: |
            mv dist ios-framework
            gcloud compute copy-files ios-framework interactivegames@gamechanger-ui1:/gamestore/drive1/games/develop --zone us-central1-b
            curl https://games.gamechanger.studio/cfp.js | node           